## CHANGE this to the name of your plugin.
name: SFBarrels

## CHANGE this to your username.
author: alexzander700

## CHANGE this to a meaningful but short description of your plugin.
description: A Slimefun4-Addon to help solve all storage issues

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.alexzander700.sfBarrels.sfBarrels

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun